name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Integration Tests 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bitcoin-version: ["24.0.1", "23.1"]
        lightningd-version: ["master", "v23.02", "v22.11.1"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build --build-arg LIGHTNINGD_VERSION=${{ matrix.lightningd-version }} \
               --build-arg BITCOIN_VERSION=${{ matrix.bitcoin-version }} \
               -t integration docker/integration/

    - name: Check directory
      run: pwd
      
    - name: Run Integration Tests 
      run: docker run -v $(pwd)/../../:/build integration 